/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ParametresRouteImport } from './routes/parametres'
import { Route as NavigateurRouteImport } from './routes/navigateur'
import { Route as ImporterRouteImport } from './routes/importer'
import { Route as HistoriqueRouteImport } from './routes/historique'
import { Route as DocumentsRouteImport } from './routes/documents'
import { Route as AssistantRouteImport } from './routes/assistant'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CriIdRouteImport } from './routes/cri.$id'

const ParametresRoute = ParametresRouteImport.update({
  id: '/parametres',
  path: '/parametres',
  getParentRoute: () => rootRouteImport,
} as any)
const NavigateurRoute = NavigateurRouteImport.update({
  id: '/navigateur',
  path: '/navigateur',
  getParentRoute: () => rootRouteImport,
} as any)
const ImporterRoute = ImporterRouteImport.update({
  id: '/importer',
  path: '/importer',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoriqueRoute = HistoriqueRouteImport.update({
  id: '/historique',
  path: '/historique',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentsRoute = DocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => rootRouteImport,
} as any)
const AssistantRoute = AssistantRouteImport.update({
  id: '/assistant',
  path: '/assistant',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CriIdRoute = CriIdRouteImport.update({
  id: '/cri/$id',
  path: '/cri/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/assistant': typeof AssistantRoute
  '/documents': typeof DocumentsRoute
  '/historique': typeof HistoriqueRoute
  '/importer': typeof ImporterRoute
  '/navigateur': typeof NavigateurRoute
  '/parametres': typeof ParametresRoute
  '/cri/$id': typeof CriIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/assistant': typeof AssistantRoute
  '/documents': typeof DocumentsRoute
  '/historique': typeof HistoriqueRoute
  '/importer': typeof ImporterRoute
  '/navigateur': typeof NavigateurRoute
  '/parametres': typeof ParametresRoute
  '/cri/$id': typeof CriIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/assistant': typeof AssistantRoute
  '/documents': typeof DocumentsRoute
  '/historique': typeof HistoriqueRoute
  '/importer': typeof ImporterRoute
  '/navigateur': typeof NavigateurRoute
  '/parametres': typeof ParametresRoute
  '/cri/$id': typeof CriIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/assistant'
    | '/documents'
    | '/historique'
    | '/importer'
    | '/navigateur'
    | '/parametres'
    | '/cri/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/assistant'
    | '/documents'
    | '/historique'
    | '/importer'
    | '/navigateur'
    | '/parametres'
    | '/cri/$id'
  id:
    | '__root__'
    | '/'
    | '/assistant'
    | '/documents'
    | '/historique'
    | '/importer'
    | '/navigateur'
    | '/parametres'
    | '/cri/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AssistantRoute: typeof AssistantRoute
  DocumentsRoute: typeof DocumentsRoute
  HistoriqueRoute: typeof HistoriqueRoute
  ImporterRoute: typeof ImporterRoute
  NavigateurRoute: typeof NavigateurRoute
  ParametresRoute: typeof ParametresRoute
  CriIdRoute: typeof CriIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/parametres': {
      id: '/parametres'
      path: '/parametres'
      fullPath: '/parametres'
      preLoaderRoute: typeof ParametresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/navigateur': {
      id: '/navigateur'
      path: '/navigateur'
      fullPath: '/navigateur'
      preLoaderRoute: typeof NavigateurRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/importer': {
      id: '/importer'
      path: '/importer'
      fullPath: '/importer'
      preLoaderRoute: typeof ImporterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/historique': {
      id: '/historique'
      path: '/historique'
      fullPath: '/historique'
      preLoaderRoute: typeof HistoriqueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documents': {
      id: '/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof DocumentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assistant': {
      id: '/assistant'
      path: '/assistant'
      fullPath: '/assistant'
      preLoaderRoute: typeof AssistantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cri/$id': {
      id: '/cri/$id'
      path: '/cri/$id'
      fullPath: '/cri/$id'
      preLoaderRoute: typeof CriIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AssistantRoute: AssistantRoute,
  DocumentsRoute: DocumentsRoute,
  HistoriqueRoute: HistoriqueRoute,
  ImporterRoute: ImporterRoute,
  NavigateurRoute: NavigateurRoute,
  ParametresRoute: ParametresRoute,
  CriIdRoute: CriIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

